# Install dependencies
FROM node:22-bullseye AS base
WORKDIR /app
COPY package*.json /app
RUN npm ci

# Boot up the app
FROM node:22-bullseye
WORKDIR /app
COPY . /app

EXPOSE 8080

CMD [ "npm", "run", "command_deploy" ]
CMD [ "npm", "run", "start" ]
