# Boot up the app
FROM node:22-bullseye

RUN ln -sf /usr/share/zoneinfo/Japan /etc/localtime

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8080

CMD [ "npm", "run", "command_deploy" ]
CMD [ "npm", "run", "start" ]
