# Install dependencies
FROM node:22-bullseye-slim as base
WORKDIR /app
COPY package*.json ./
RUN npm ci

# Boot up the app
FROM node:22-bullseye-slim
WORKDIR /app
COPY . /app

EXPOSE 8080

CMD [ "npm", "run", "command_deploy" ]
CMD [ "npm", "run", "start" ]
